name: Check

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Check spelling
        shell: bash
        run: npm run spellcheck -- .

      - name: Format and lint
        shell: bash
        run: npm run stylecheck -- --no-errors-on-unmatched

      - name: Check ES5 artifacts
        shell: bash
        run: npm run es5check

      - name: Check types
        shell: bash
        run: npm run typecheck

      - name: Test
        shell: bash
        run: npm run test
