# Based on https://docs.github.com/ja/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages
name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry Run
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  define_variables_to_publish:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Define variables
        id: define_variables
        shell: bash
        run: |
          version=$(jq -r .version package.json)
          echo "version: $version"
          with_next_tag=no
          if [[ $version == *-* ]]; then
            next_tagged_version=$(npm view viewport-extra dist-tags.next)
            echo "next_tagged_version: $next_tagged_version"
            greater_version=$(npx semver "$version" "$next_tagged_version" | tail -n 1)
            if [[ $version == $greater_version ]]; then
              with_next_tag=yes
            fi
          fi
          echo "with_next_tag: $with_next_tag"
          echo "with_next_tag=$with_next_tag" >> $GITHUB_OUTPUT
    outputs:
      with_next_tag: ${{ steps.define_variables.outputs.with_next_tag }}

  publish:
    needs: define_variables_to_publish
    if: inputs.dry_run == false
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build & npm run declare

      - name: Publish to npm
        if: needs.define_variables_to_publish.outputs.with_next_tag == 'no'
        shell: bash
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to npm with next tag
        if: needs.define_variables_to_publish.outputs.with_next_tag == 'yes'
        shell: bash
        run: npm publish --provenance --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  dry_publish:
    needs: define_variables_to_publish
    if: inputs.dry_run == true
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build & npm run declare

      - name: Publish to npm
        if: needs.define_variables_to_publish.outputs.with_next_tag == 'no'
        shell: bash
        run: npm publish --provenance --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to npm with next tag
        if: needs.define_variables_to_publish.outputs.with_next_tag == 'yes'
        shell: bash
        run: npm publish --provenance --dry-run --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
