# Based on https://docs.github.com/ja/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages
name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry Run
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  define_variables_to_publish:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Define variables
        id: define_variables
        shell: bash
        run: |
          version=$(jq -r .version package.json)
          echo "version: $version"
          dist_tag=temporary
          if [[ $version == *-* ]]; then
            next_tagged_version=$(npm view viewport-extra dist-tags.next)
            echo "next_tagged_version: $next_tagged_version"
            greater_version=$(npx semver "$version" "$next_tagged_version" | tail -n 1)
            if [[ $version == $greater_version ]]; then
              dist_tag=next
            fi
          else
            latest_tagged_version=$(npm view viewport-extra dist-tags.latest)
            echo "latest_tagged_version: $latest_tagged_version"
            greater_version=$(npx semver "$version" "$latest_tagged_version" | tail -n 1)
            if [[ $version == $greater_version ]]; then
              dist_tag=latest
            fi
          fi
          echo "dist_tag: $dist_tag"
          echo "dist_tag=$dist_tag" >> $GITHUB_OUTPUT
    outputs:
      dist_tag: ${{ steps.define_variables.outputs.dist_tag }}

  publish:
    needs: define_variables_to_publish
    if: inputs.dry_run == false
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build & npm run declare

      - name: Publish to npm
        shell: bash
        run: npm publish --tag ${{ needs.define_variables_to_publish.outputs.dist_tag }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Remove temporary dist-tag
        if: needs.define_variables_to_publish.outputs.dist_tag == 'temporary'
        shell: bash
        run: npm dist-tag rm viewport-extra temporary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  dry_publish:
    needs: define_variables_to_publish
    if: inputs.dry_run == true
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Build
        shell: bash
        run: npm run build & npm run declare

      - name: Publish to npm
        shell: bash
        run: npm publish --tag ${{ needs.define_variables_to_publish.outputs.dist_tag }} --provenance --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
