name: Validate

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install packages
        shell: bash
        run: npm ci

      - name: Format
        shell: bash
        run: npx prettier . '!examples/**' '!.release-please-manifest.json' '!CHANGELOG.md' --ignore-path .gitignore --check

      # Disable ignoring filenames that starts with dot
      # https://stackoverflow.com/a/71829427
      - name: Lint
        shell: bash
        run: npx eslint . --ignore-pattern '/examples/' --ignore-path .gitignore --ignore-pattern '!.*' --max-warnings 0

      - name: Test
        shell: bash
        run: npm t
